#!/usr/bin/env bash
set -euo pipefail
set -x

docker-compose exec \
  --env SNOWFLAKE_USERNAME="${SNOWFLAKE_USERNAME}" \
  --env SNOWFLAKE_PASSWORD="${SNOWFLAKE_PASSWORD}" \
  --env SNOWFLAKE_DATABASE="${SNOWFLAKE_DATABASE}" \
  --env SNOWFLAKE_ROLE="${SNOWFLAKE_ROLE}" \
  --env SNOWFLAKE_SCHEMA="${SNOWFLAKE_SCHEMA}" \
  --env SNOWFLAKE_URL="${SNOWFLAKE_URL}" \
  --env SNOWFLAKE_WAREHOUSE="${SNOWFLAKE_WAREHOUSE}" \
  spark-client ./bin/spark-submit \
  --master ${SPARK_MASTER_URL} \
  --conf spark.executor.cores=${SPARK_EXECUTOR_CORES} \
  --conf spark.executor.memory=${SPARK_EXECUTOR_MEMORY} \
  --conf spark.driver.memory=${SPARK_DRIVER_MEMORY} \
  "${@}"

# --packages net.snowflake:snowflake-jdbc:3.12.12,net.snowflake:spark-snowflake_2.12:2.8.2-spark_3.0,org.elasticsearch:elasticsearch-spark-30_2.12:7.15.0 \
