#!/usr/bin/env bash
set -euo pipefail

DOCKER_COMPOSE_ENV_STRING=$(printenv | grep -E '(SPARK|SNOWFLAKE)' | awk '{print "--env " $1 }')

set -x

docker-compose exec \
  $DOCKER_COMPOSE_ENV_STRING \
  spark-client ./bin/spark-submit \
  --master ${SPARK_MASTER_URL} \
  --conf spark.executor.cores=${SPARK_EXECUTOR_CORES} \
  --conf spark.executor.memory=${SPARK_EXECUTOR_MEMORY} \
  --conf spark.driver.memory=${SPARK_DRIVER_MEMORY} \
  "${@}"
